### ISSUE TITLE
bootiful-microservices-camden version ran into authentication issue

### ISSUE THREAD

**Issue by xmkevinchen** [joshlong/bootiful-microservices#8]
Hi I'm a newbie of SpringCloud thing. The `bootiful-microservice-brixton` project ran well for me, however `bootiful-microservices-camden` ran into authentication issue, kept asking about the user / password or getting response via curl
```
curl 'http://localhost:9999/reservations/names'
{
  "timestamp":1481177384200,
  "status":401,
  "error":"Unauthorized",
  "message":"Full authentication is required to access this resource",
  "path":"/reservations/names"
}
```

**Comment by xmkevinchen** [comment]
Figure out something, but still don't understand the mechanism now

1. Getting `access_token`
```
curl http://acme:acmesecret@localhost:9191/uaa/oauth/token -d grant_type=password -d username=jlong -d password=spring

{"access_token":"af3a3e2e-29f3-437b-baf4-47b32e4c1244","token_type":"bearer","expires_in":43199,"scope":"openid"}
```

2. Use `access_token` to call API
```
curl -D- 'http://localhost:9999/reservations/names' -H "Authorization: bearer af3a3e2e-29f3-437b-baf4-47b32e4c1244"

["Josh","Dr. Johnson","Dr. Syer","Dr. Pollack"]
```

**Comment by marcingrzejszczak** [comment]
@xmkevinchen  In order to send the request to an app that is secured you need a token. Here you have that in the scripts - https://github.com/joshlong/bootiful-microservices/blob/master/scripts/scenario_camden_tester.sh#L84-L86 . This is how we get a token - https://github.com/joshlong/bootiful-microservices/blob/master/scripts/common.sh#L169-L180 . This is how we attach the token to the request https://github.com/joshlong/bootiful-microservices/blob/master/scripts/common.sh#L91-L105
